name: CI


on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Run lint
        run: bun run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Run typecheck
        run: bun run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Run tests
        run: bun run test run

  dockerci:
    name: Docker CI
    needs: [lint, typecheck, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/hydra-network/linky:${{ env.IMAGE_TAG }}
          docker tag ghcr.io/hydra-network/linky:${{ env.IMAGE_TAG }} ghcr.io/hydra-network/linky:latest

      - name: Push Docker containers
        run: |
          docker push ghcr.io/hydra-network/linky:${{ env.IMAGE_TAG }}
          docker push ghcr.io/hydra-network/linky:latest

  changelog:
    name: Changelog
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
